# Generated by Django 4.2.2 on 2023-06-15 18:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100, unique=True)),
                ("image_url", models.ImageField(upload_to="")),
                ("url", models.URLField(max_length=100)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
            ],
        ),
    ]
