# Generated by Django 4.2.2 on 2023-06-15 19:21

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiscData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("data", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("image_url", models.ImageField(upload_to="")),
                ("url", models.URLField(max_length=100, null=True)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("profile", models.CharField(max_length=100)),
                ("image_url", models.ImageField(upload_to="")),
                ("description", models.CharField(blank=True, max_length=500)),
                ("linkedin", models.URLField(max_length=100, null=True)),
                ("email", models.URLField(max_length=100, null=True)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("profile", models.CharField(max_length=100)),
                ("comment", models.CharField(max_length=500)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(max_length=100, null=True),
        ),
    ]
