# Generated by Django 4.2.2 on 2023-06-15 19:25

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_miscdata_project_teammember_testimonial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscdata",
            name="created_date",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="miscdata",
            name="updated_date",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, null=True
            ),
        ),
    ]
